apiVersion: route.openshift.io/v1                                         
kind: Route                                                               
metadata:                                                                 
  name: gabriella-nginx-demo                                                        
  labels:                                                                 
    app: gabriella-nginx-demo                                                       
spec:                                                                     
  to:                                                                     
    kind: Service                                                         
    name: gabriella-nginx-demo                                                      
    weight: 100
